import SupportSection from "@/components/Support";
import { Metadata } from "next";
import siteConfig from '../../../../siteConfig';
import PageTitle from "../../../components/Common/PageTitle";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const pageTitle = `2257 | ${siteConfig.siteName}`;
const pageDescription = `Explore our 18 U.S.C. § 2257 Record Keeping Requirements Compliance Statement to understand the rules and guidelines governing the use of our image editing platform. Stay informed about your rights and responsibilities as a user to ensure a compliant and enjoyable experience.`;

export const metadata: Metadata = {
  title: pageTitle,
  description: pageDescription,
};

const TwoTwoFiveSevenPage = () => {

  return (
    <>
       <Header />
      <section className="pt-3 pb-25">
        <div className="max-w-[1170px]  mx-auto text-[black]/70 dark:text-[white]/50 px-4 sm:px-8 xl:px-0 z-10 pt-25">
          <PageTitle title="18 U.S.C. § 2257 Record Keeping Requirements Compliance Statement" paragraph="Updated: February 19th, 2024" />

          <div className="mt-8">
            <p className="mt-4">The operator of {siteConfig.shortURL} is not the producer (whether primary or secondary as defined in 18 U.S.C. § 2257) of any of the content found on {siteConfig.shortURL}. Our activities are limited to the transmission, storage, retrieval, hosting, and/or formatting of text-to-image conversions generated by third-party users (&quot;Verified Users&quot;).</p>

            <h2 className="mt-8 text-2xl font-bold">Exemption: Content Produced by Third Parties</h2>
            <p className="mt-4">All portions of the website containing user-generated material are under the control of the relevant Verified User, for whom this platform is provided as an online service. Pursuant to 18 U.S.C. § 2257(h)(2)(B)(v) and 47 U.S.C. § 230(c), {siteConfig.shortURL} reserves the right to delete materials that are deemed, in our sole discretion, to be inconsistent with our Terms of Service.</p>

            <h2 className="mt-8 text-2xl font-bold">Exemption: Content Produced by Website Operators</h2>
            <p className="mt-4">For the avoidance of doubt, no images appearing on this website depict actual human beings. Furthermore, no images uploaded by users, nor any images generated by users that are derived from or based upon images uploaded by users, are ever displayed on this website. All visual depictions are synthesized through artificial intelligence algorithms and are therefore exempt from the requirements of 18 U.S.C. § 2257 and 28 C.F.R. § 75.</p>

            <h2 className="mt-8 text-2xl font-bold">Designated Records Custodian</h2>
            <p className="mt-4">While we do not produce the content, we have designated a custodian to be the keeper of original records for all marketing and advertising materials that are within the scope of 18 U.S.C. § 2257 and 28 C.F.R. § 75.</p>

            <h2 className="mt-8 text-2xl font-bold">Age Verification and Compliance Procedures</h2>
            <p className="mt-4">All Verified Users of {siteConfig.shortURL} must be over eighteen (18) years of age. They are personally identified and verified by {siteConfig.shortURL} prior to uploading, generating, sharing, displaying and downloading content.
Verified Users must provide evidence or certify that all AI-generated depictions are compliant with age and consent requirements, as well as record-keeping requirements under 18 U.S.C. § 2257.</p>

            <h2 className="mt-8 text-2xl font-bold">Further Assistance</h2>
            <p className="mt-4">For further assistance or questions regarding this notice, please contact our compliance department at {siteConfig.supportEmail}</p>

          </div>
        </div>
      </section>
      <Footer /> 
    </>
  );
};

export default TwoTwoFiveSevenPage;

