const siteConfig = {
  gitHubRepo: "https://github.com/mattphelps/cc-template",
  siteName: "CC Template",
  siteURL: "https://cc.template",
  shortURL: "cc.template",
  siteTitle: "Best Credit Cards in CC - Top 10",
  siteDescription: "",
  faviconPath: "/favicons.ico",
  emailFormLink: "https://formspree.io/f/xwkgkdjq",
  buttonColor: "#685cf4",
  buttonColor2: "#ff9900",
  GATag: "G-FBFEVVB9JF",
  hrefLang: "",
  regionCode: "",
  supportEmail: "matt@leandme.com",
  ccAffLink1: "", 
  ccAffLink2: "", 
  ccAffLink3: "", 
  ccAffLink4: "", 
  ccAffLink5: "", 
  ccAffLink6: "", 
  ccAffLink7: "", 
  ccAffLink8: "", 
  ccAffLink9: "", 
  ccAffLink10: "", 
};

export default siteConfig;
