const siteConfig = {
  gitHubRepo: "https://github.com/mattphelps/bcc-de",
  siteName: "Credit Cards Germany",
  siteURL: "https://creditcardgermany.de",
  shortURL: "creditcardgermany.de",
  siteTitle: "Best Credit Cards in Germany - Top 10",
  siteDescription: "",
  faviconPath: "/favicon.ico",
  emailFormLink: "https://formspree.io/f/xwkgkdjq",
  buttonColor: "#685cf4",
  buttonColor2: "#ff9900",
  GATag: "G-FBFEVVB9JF",
  country: "Germany",
  hrefLang: "en-DE",
  regionCode: "DE",
  supportEmail: "matt@leandme.com",
  ccAffLink1: "",
  ccAffLink2: "",
  ccAffLink3: "",
  ccAffLink4: "",
  ccAffLink5: "",
  ccAffLink6: "",
  ccAffLink7: "",
  ccAffLink8: "",
  ccAffLink9: "",
  ccAffLink10: "",
};

export default siteConfig;