const siteConfig = {
  gitHubRepo: "https://github.com/mattphelps/bcc-in",
  siteName: "Best Credit Cards India",
  siteURL: "https://bestcreditcard.co.in",
  shortURL: "bestcreditcard.co.in",
  siteTitle: "Best Credit Cards in India - Top 10",
  siteDescription: "",
  faviconPath: "/favicon.ico",
  emailFormLink: "https://formspree.io/f/xwkgkdjq",
  buttonColor: "#685cf4",
  buttonColor2: "#ff9900",
  GATag: "G-FBFEVVB9JF",
  country: "India",
  hrefLang: "en-IN",
  regionCode: "IN",
  supportEmail: "matt@leandme.com",
  ccAffLink1: "",
  ccAffLink2: "",
  ccAffLink3: "",
  ccAffLink4: "",
  ccAffLink5: "",
  ccAffLink6: "",
  ccAffLink7: "",
  ccAffLink8: "",
  ccAffLink9: "",
  ccAffLink10: "",
};

export default siteConfig;