import { FAQ } from "@/types/faq";


const homeFaqData: FAQ[] = [
  {
    id: 74,
    question: `How does the AI tattoo generator work?`,
    answer:
     `Think of our AI tattoo generator as your personal digital tattoo designer. Just type your tattoo dreams into the prompt field, and watch our tattoo creator work its magic. It's like having a chat with a creative tattoo artist who turns your words into an amazing tattoo design.`,
  },
  {
    id: 75,
    question: `What kind of inputs does the AI require to design a tattoo?`,
    answer:
     `Our tattoo maker loves details! Tell us all about your dream tattoo - the more you share, the better our tattoo design generator can whip up something that's totally “you”. It's like painting a picture with words and watching our AI bring it to life. We also have styles and color options input to further customize your design.`,
  },
  {
    id: 76,
    question: `Can I customize or modify the designs generated by the AI?`,
    answer:
    `Of course! Our AI tattoo designs can create your final output or they can be used as just a starting point. Feel free to tweak and play around with them. It's all about making sure your final tattoo is as unique and awesome as you are.`,
  },
  {
    id: 78,
    question: `How unique are the tattoos designed by the AI?`,
    answer:
    `100% unique! Our AI-generated tattoos are completely unique – no two are the same. We make sure that your design is as original and special as your idea. Our powerful AI synthesizes every single concept from scratch so there is no repeated design - ever.`,
  },
  {
    id: 79,
    question: `How does the AI handle different tattoo styles?`,
    answer:
    `Our AI for tattoos is a true master of different styles. Whether you're into traditional, tribal, watercolor, or any other ink style, our AI tattoo designer has got the skills to match. It's like having a little tattoo studio in your pocket - so what are you waiting for?`,
  },
  {
    id: 80,
    question: `Is there a way to preview the tattoo on my body using the AI?`,
    answer:
    `Not at this moment. We are working on a tattoo simulator which lets you try your design on for size, virtually. It's a fun way to see how your tattoo will look on your skin, helping you decide where it'll look best. Make sure to bookmark our tattoo design website and stay tuned for this update in the near future.`,
  },
  {
    id: 81,
    question: `How do I request changes to a design?`,
    answer:
    `You can generate as many designs as you want. If you don’t like the concept, simply try another prompt into the input field. Try to be as descriptive as you can as our AI performs best when you give it a descriptive input.`,
  },
  {
    id: 82,
    question: `Are the designs I create kept private?`,
    answer:
    `If you are on the basic plan, then your designs are added to our exploration gallery. But if you want to keep your designs private, you can upgrade to the pro plan which allows you to keep the designs private.`,
  },
  {
    id: 83,
    question: `Do you offer a random tattoo generator?`,
    answer:
    `Not quite, you have to provide an input prompt for the tattoo concept you want. However, we provide a “surprise me” button when it comes to style selection. This feature adds an element of spontaneity, offering unexpected and exciting results for your tattoo design`,
  }
];

export default homeFaqData;
