import { Ideas } from "@/types/ideas";

export const placementIdeasData: Ideas[] = [
    {
        id: 1,
        title: "Sleeve Tattoo Ideas",
        label: "Sleeve",
        image: "/styles/abstract.png",
        description: "",
        slug: "/sleeve",
        count: 0,
    },
    {
        id: 2,
        title: "Back Tattoo Ideas",
        label: "Back",
        image: "/styles/abstract.png",
        description: "",
        slug: "/back",
        count: 0,
    },
    {
        id: 3,
        title: "Hand Tattoo Ideas",
        label: "Hand",
        image: "/styles/abstract.png",
        description: "",
        slug: "/hand",
        count: 0,
    },
    {
        id: 4,
        title: "Finger Tattoo Ideas",
        label: "Finger",
        image: "/styles/abstract.png",
        description: "",
        slug: "/finger",
        count: 0,
    },
    {
        id: 5,
        title: "Forearm Tattoo Ideas",
        label: "Forearm",
        image: "/styles/abstract.png",
        description: "",
        slug: "/forearm",
        count: 0,
    },
    {
        id: 6,
        title: "Neck Tattoo Ideas",
        label: "Neck",
        image: "/styles/abstract.png",
        description: "",
        slug: "/neck",
        count: 0,
    },
    {
        id: 7,
        title: "Arm Tattoo Ideas",
        label: "Arm",
        image: "/styles/abstract.png",
        description: "",
        slug: "/arm",
        count: 0,
    },
    {
        id: 8,
        title: "Sternum Tattoo Ideas",
        label: "Sternum",
        image: "/styles/abstract.png",
        description: "",
        slug: "/sternum",
        count: 0,
    },
    {
        id: 9,
        title: "Eye Tattoo Ideas",
        label: "Eye Tattoo",
        image: "/styles/abstract.png",
        description: "",
        slug: "/eye",
        count: 0,
    },
    {
        id: 10,
        title: "Shoulder Tattoo Ideas",
        label: "Shoulder Tattoo",
        image: "/styles/abstract.png",
        description: "",
        slug: "/shoulder",
        count: 0,
    },
]


export const popularIdeasData: Ideas[] = [
    {
        id: 1,
        title: "Butterfly Tattoo Ideas",
        label: "butterfly",
        image: "/styles/abstract.png",
        description: "",
        slug: "/butterfly",
        count: 0,
    },
    {
        id: 2,
        title: "Tattoo Ideas for Men",
        label: "For Men",
        image: "/styles/abstract.png",
        description: "",
        slug: "/men",
        count: 0,
    },
    {
        id: 3,
        title: "Medusa Tattoo Ideas",
        label: "Medusa",
        image: "/styles/abstract.png",
        description: "",
        slug: "/medusa",
        count: 0,
    },
    {
        id: 4,
        title: "Minimalist Tattoo Ideas",
        label: "Minimalist",
        image: "/styles/abstract.png",
        description: "",
        slug: "/minimalist",
        count: 0,
    },
    {
        id: 5,
        title: "Semicolon Tattoo Ideas",
        label: "Semicolon",
        image: "/styles/abstract.png",
        description: "",
        slug: "/semicolon",
        count: 0,
    },
    {
        id: 6,
        title: "Snake Tattoo Ideas",
        label: "Snake",
        image: "/styles/abstract.png",
        description: "",
        slug: "/snake",
        count: 0,
    },
    {
        id: 7,
        title: "Small Tattoo Ideas",
        label: "Small Tattoos",
        image: "/styles/abstract.png",
        description: "",
        slug: "/small",
        count: 0,
    },
    {
        id: 8,
        title: "Dragon Tattoo Ideas",
        label: "Dragon Tattoos",
        image: "/styles/abstract.png",
        description: "",
        slug: "/dragon",
        count: 0,
    },
    {
        id: 9,
        title: "Memento Mori Tattoo Ideas",
        label: "Memento Mori",
        image: "/styles/abstract.png",
        description: "",
        slug: "/memento-mori",
        count: 0,
    },
    {
        id: 10,
        title: "Cat Tattoo Ideas",
        label: "Cat",
        image: "/styles/abstract.png",
        description: "",
        slug: "/cat",
        count: 0,
    },
]


export const ideasData: Ideas[] = [
    
    {
        id: 2,
        title: "Tattoo Ideas for Women",
        label: "For Women",
        image: "/styles/abstract.png",
        description: "",
        slug: "/women",
        count: 0,
    },
    {
        id: 3,
        title: "Tattoo Sleeve Ideas",
        label: "Sleeve",
        image: "/styles/abstract.png",
        description: "",
        slug: "/sleeve",
        count: 0,
    },
    {
        id: 5,
        title: "Small Tattoo Ideas",
        label: "Small",
        image: "/styles/abstract.png",
        description: "",
        slug: "/small",
        count: 0,
    },
    {
        id: 7,
        title: "Fine Line Tattoo Ideas",
        label: "Fine Line",
        image: "/styles/abstract.png",
        description: "",
        slug: "/fine-line",
        count: 0,
    },
    {
        id: 10,
        title: "Forearm Tattoo Ideas",
        label: "Forearm",
        image: "/styles/abstract.png",
        description: "",
        slug: "/forearm",
        count: 0,
    },
]

