import { Ideas } from "@/types/ideas";

export const placementIdeasData: Ideas[] = [
    {
        id: 1,
        title: "Sleeve",
        keyword: "Sleeve Tattoo Ideas",
        image: "/styles/abstract.png",
        description: "",
        slug: "/sleeve",
        count: 0,
    },
    {
        id: 2,
        title: "Back",
        keyword: "Back Tattoo Ideas",
        image: "/styles/abstract.png",
        description: "",
        slug: "/back",
        count: 0,
    },
    {
        id: 3,
        title: "Hand",
        keyword: "Hand Tattoo Ideas",
        image: "/styles/abstract.png",
        description: "",
        slug: "/hand",
        count: 0,
    },
    {
        id: 4,
        title: "Finger",
        keyword: "Finger Tattoo Ideas",
        image: "/styles/abstract.png",
        description: "",
        slug: "/finger",
        count: 0,
    },
    {
        id: 5,
        title: "Forearm",
        keyword: "Forearm Tattoo Ideas",
        image: "/styles/abstract.png",
        description: "",
        slug: "/forearm",
        count: 0,
    },
    {
        id: 6,
        title: "Neck",
        keyword: "Neck Tattoo Ideas",
        image: "/styles/abstract.png",
        description: "",
        slug: "/neck",
        count: 0,
    },
    {
        id: 7,
        title: "Arm",
        keyword: "Arm Tattoo Ideas",
        image: "/styles/abstract.png",
        description: "",
        slug: "/arm",
        count: 0,
    },
    {
        id: 8,
        title: "Sternum",
        keyword: "Sternum Tattoo Ideas",
        image: "/styles/abstract.png",
        description: "",
        slug: "/sternum",
        count: 0,
    },
    {
        id: 9,
        title: "Eye Tattoo",
        keyword: "Eye Tattoo Ideas",
        image: "/styles/abstract.png",
        description: "",
        slug: "/eye",
        count: 0,
    },
    {
        id: 10,
        title: "Shoulder Tattoo",
        keyword: "Shoulder Tattoo Ideas",
        image: "/styles/abstract.png",
        description: "",
        slug: "/shoulder",
        count: 0,
    },
]


export const popularIdeasData: Ideas[] = [
    {
        id: 1,
        title: "butterfly",
        keyword: "Butterfly Tattoo Ideas",
        image: "/styles/abstract.png",
        description: "",
        slug: "/butterfly",
        count: 0,
    },
    {
        id: 2,
        title: "For Men",
        keyword: "Tattoo Ideas for Men",
        image: "/styles/abstract.png",
        description: "",
        slug: "/men",
        count: 0,
    },
    {
        id: 3,
        title: "Medusa",
        keyword: "Medusa Tattoo Ideas",
        image: "/styles/abstract.png",
        description: "",
        slug: "/medusa",
        count: 0,
    },
    {
        id: 4,
        title: "Minimalist",
        keyword: "Minimalist Tattoo Ideas",
        image: "/styles/abstract.png",
        description: "",
        slug: "/minimalist",
        count: 0,
    },
    {
        id: 5,
        title: "Semicolon",
        keyword: "Semicolon Tattoo Ideas",
        image: "/styles/abstract.png",
        description: "",
        slug: "/semicolon",
        count: 0,
    },
    {
        id: 6,
        title: "Snake",
        keyword: "Snake Tattoo Ideas",
        image: "/styles/abstract.png",
        description: "",
        slug: "/snake",
        count: 0,
    },
    {
        id: 7,
        title: "Small Tattoos",
        keyword: "Small Tattoo Ideas",
        image: "/styles/abstract.png",
        description: "",
        slug: "/small",
        count: 0,
    },
    {
        id: 8,
        title: "Dragon Tattoos",
        keyword: "Dragon Tattoo Ideas",
        image: "/styles/abstract.png",
        description: "",
        slug: "/dragon",
        count: 0,
    },
    {
        id: 9,
        title: "Memento Mori",
        keyword: "Memento Mori Tattoo Ideas",
        image: "/styles/abstract.png",
        description: "",
        slug: "/memento-mori",
        count: 0,
    },
    {
        id: 10,
        title: "Cat",
        keyword: "Cat Tattoo Ideas",
        image: "/styles/abstract.png",
        description: "",
        slug: "/cat",
        count: 0,
    },
]


export const ideasData: Ideas[] = [
    
    {
        id: 2,
        title: "For Women",
        keyword: "Tattoo Ideas for Women",
        image: "/styles/abstract.png",
        description: "",
        slug: "/women",
        count: 0,
    },
    {
        id: 3,
        title: "Sleeve",
        keyword: "attoo Sleeve Ideas",
        image: "/styles/abstract.png",
        description: "",
        slug: "/sleeve",
        count: 0,
    },
    {
        id: 5,
        title: "Small",
        keyword: "Small Tattoo Ideas",
        image: "/styles/abstract.png",
        description: "",
        slug: "/small",
        count: 0,
    },
    {
        id: 7,
        title: "Fine Line",
        keyword: "Fine Line Tattoo Ideas",
        image: "/styles/abstract.png",
        description: "",
        slug: "/fine-line",
        count: 0,
    },
    {
        id: 10,
        title: "Forearm",
        keyword: "Forearm Tattoo Ideas",
        image: "/styles/abstract.png",
        description: "",
        slug: "/forearm",
        count: 0,
    },
]

